deploy:
  stage: deploy
  only:
    - master
  script:
    - imagefile=$(nix-build dockerimage.nix)
    - docker rmi -f matrix-ical-bot:latest || true
    - docker load < $imagefile
    - docker tag matrix-ical-bot:latest $HOST_REGISTRY/matrix-ical-bot:latest
    - docker login -u $USER_REGISTRY -p $PW_REGISTRY $HOST_REGISTRY
    - docker push $HOST_REGISTRY/matrix-ical-bot:latest
