name: matrix-ical-bot
version: '0.1.0.0'
synopsis: Bot that listens for ical file system changes and posts them to matrix rooms
category: Web
author: plapadoo UG (haftungsbeschränkt)
maintainer: middendorf@plapadoo.de
copyright: plapadoo UG (haftungsbeschränkt) 2017
license: BSD3
github: plapadoo/matrix-ical-bot
extra-source-files:
- README.md
default-extensions:
- OverloadedStrings
- NoImplicitPrelude
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
dependencies:
- base
- iCalendar
- matrix-bot-api
- dhall
- text-format
- text
- fsnotify
- directory
- data-default
- lucid
- containers
- time
executables:
  matrix-mail-bot-exe:
    main: Main.hs
    source-dirs: app
